# Generated by Django 5.1.2 on 2024-11-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_contact_alter_product_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Электронная почта"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="message",
            field=models.CharField(max_length=255, verbose_name="Сообщение"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Имя"),
        ),
    ]
